# Common application configuration
spring:
  application:
    name: PixelTrade
  profiles:
    active: prod
  freemarker:
    charset: UTF-8
    template-loader-path: classpath:/templates/
  data:
    redis:
      repositories:
        enabled: false
  cache:
    redis:
      time-to-live: 10m
    type: redis

token:
  expiration:
    access: 86400000    # 24 hours
    refresh: 604800000  # 7 days
  secret-key: vpwGiG8Hh659YkRNBnBZXW1a6pRWSfLBKyd4f4MigA8


#  spring:
#     mail:
#    host: sandbox.smtp.mailtrap.io
#    port: 587
#    username: 2c931fe2fc5a6a
#    password: b4b4f8dabf1183
#    properties:
#      smtp:
#        auth: true
#        starttls:
#          enable: true

