# Common application configuration
spring:
  application:
    name: PixelTrade
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
token:
  expiration:
    access: 86400000    # 24 hours
    refresh: 604800000  # 7 days
  secret-key: vpwGiG8Hh659YkRNBnBZXW1a6pRWSfLBKyd4f4MigA8

# Production-specific configuration
---
spring:
  config:
    activate:
      on-profile: prod
  task:
    execution:
      pool:
        core-size: 20
        max-size: 100
        keep-alive: 60s
        queue-capacity: 500
      thread-name-prefix: prod-
  datasource:
    url: jdbc:postgresql://localhost:5432/pixeltrade
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: abbos2004postgres
  h2:
    console:
      enabled: false
server:
  port: 8080
app:
  log: true  # GLOBAL LOGGING



#  mail:
#    host: sandbox.smtp.mailtrap.io
#    port: 587
#    username: 2c931fe2fc5a6a
#    password: b4b4f8dabf1183
#    properties:
#      smtp:
#        auth: true
#        starttls:
#          enable: true

